// [plain, slop] pairs. slopify: plain -> slop. unslopify: slop -> plain.
const SLOP_PAIRS = [
  // business jargon
  ["use", "leverage"],
  ["team work", "synergy"],
  ["new", "revolutionary"],
  ["change", "paradigm shift"],
  ["improve", "supercharge"],
  ["best", "world-class"],
  ["quality", "best-in-class"],
  ["combine", "unlock synergies between"],
  ["plan", "strategic roadmap"],
  ["goal", "north star"],
  ["work together", "collaborate cross-functionally"],
  ["important", "mission-critical"],
  ["basic", "foundational"],
  ["fast", "lightning-fast"],
  ["easy", "seamless"],
  ["help", "empower"],
  ["big", "game-changing"],
  ["idea", "innovative solution"],
  ["update", "enhancement"],
  ["think about", "deep dive into"],
  ["look at", "circle back on"],
  ["talk", "align"],
  ["start", "kick off"],
  ["end result", "net-net"],
  ["basically", "at the end of the day"],
  ["good", "amazing"],
  ["cheap", "cost-effective"],
  ["flexible", "agile"],
  ["reliable", "enterprise-grade"],
  ["custom", "tailored"],
  ["all-in-one", "holistic"],
  ["automatic", "intelligent"],
  ["online", "cloud-based"],
  ["simple", "streamlined"],
  ["strong", "robust"],
  ["different", "disruptive"],
  ["future", "next-generation"],
  ["complete", "end-to-end"],
  ["together", "in lockstep"],
  ["priority", "top-of-mind"],
  ["focus on", "double down on"],
  ["plan ahead", "get ahead of the curve"],
  ["team", "dream team"],
  ["growth", "hypergrowth"],
  ["users", "valued customers"],
  ["features", "capabilities"],
  ["problem", "pain point"],
  ["solution", "value proposition"],
  ["meeting", "touch base"],
  ["explain", "unpack"],
  ["review", "circle back and align on"],
  ["overview", "bird's-eye view"],
  ["skills", "core competencies"],
  ["experience", "customer journey"],
  ["result", "impact"],
  ["data", "actionable insights"],
  ["plan for growth", "scale strategically"],
  ["worker", "changemaker"],
  ["smart", "cutting-edge"],
  ["unique", "one-of-a-kind"],

  // clickbait / headline slop
  ["is kind of interesting", "will blow your mind"],
  ["here is", "you won't believe"],
  ["notable", "shocking"],
  ["detail", "secret"],
  ["some disagree with", "experts hate"],
  ["changed a few things", "changed everything"],
  ["one method", "one weird trick"],
  ["some doctors mention", "doctors don't want you to know"],
  ["here is why, maybe", "this is why"],
  ["number is fairly ordinary", "number will surprise you"],
  ["what happened afterward", "what happened next"],
  ["got some attention online", "is going viral"],
  ["made some noise online", "broke the internet"],
  ["some people mentioned", "everyone is talking about"],
  ["you might want to look at this", "you need to see this"],
  ["might be somewhat useful", "will change your life"],
  ["remarkable", "mind-blowing"],
  ["surprising", "jaw-dropping"],
  ["unusual", "unbelievable"],
  ["excessive", "insane"],
  ["fairly good", "incredible"],
  ["somewhat helpful", "life-changing"],
  ["modest improvement", "game changer"],
  ["guide", "ultimate guide"],
  ["some things worth knowing", "everything you need to know"],
  ["some facts about", "the truth about"],
  ["described", "exposed"],
  ["found the following", "can't believe what happened"],
  ["is fairly interesting", "will leave you speechless"],
  ["this method", "this one trick"],
  ["disagree", "hate them"],
  ["restricted", "banned"],
  ["criticism", "outrage"],
  ["criticized", "slammed"],
  ["critiques", "destroys"],
  ["responds to", "obliterates"],
  ["eye-catching", "stunning"],
  ["you should see this", "you won't believe this"],
  ["a small change", "this tiny change"],
  ["something nobody explains", "the number no one explains"],
  ["you're doing it differently", "you're doing this wrong"],
  ["what matters", "what actually matters"],

  // vague corporate filler
  ["really", "actually"],
  ["overall", "at a high level"],
  ["in summary", "to synthesize"],
  ["quickly", "at pace"],
  ["carefully", "with intentionality"],
  ["clearly", "with clarity"],
  ["as needed", "on an as-needed basis, going forward"],
  ["now", "at this juncture"],
  ["soon", "in the near-term horizon"],
  ["plan to", "are poised to"],
  ["hope to", "aim to strategically"],
  ["want", "are excited to"],
  ["try to", "endeavor to"],
  ["ask", "reach out to"],
  ["tell", "loop in"],
  ["decide", "make a data-driven decision"],
  ["guess", "hypothesize"],
  ["check", "validate"],
  ["fix", "remediate"],
  ["problem area", "opportunity for improvement"],
  ["mistake", "learning opportunity"],
  ["failure", "pivot"],
  ["cut costs", "optimize spend"],
  ["fire", "restructure the team, impacting"],
  ["layoffs", "workforce optimization"],

  // sourced from salesforce.com marketing copy
  ["company using AI agents", "agentic enterprise"],
  ["useful data", "actionable intelligence"],
  ["one accurate record", "single source of truth"],
  ["one dashboard", "single pane of glass"],
  ["full picture", "360° view"],
  ["software automation", "digital labor"],
  ["automatic ticket resolution", "autonomous case resolution"],
  ["combined live data", "unified, real-time data"],
  ["well-managed data", "governed, trusted data foundation"],
  ["share knowledge clearly", "deliver expertise simply"],
  ["help customers and employees", "drive customer and employee success"],
  ["grow safely", "scale securely"],
  ["good, reliable experience", "premium, consistent experience"],
  ["personalization throughout the buying process", "personalisation across customer journey"],
  ["timely, relevant message", "right time with the right message"],
  ["work at their own pace", "move at their natural tempo"],
  ["doing what we said", "walking the walk"],
  ["combined platform", "deeply unified platform"],
  ["constant growth", "non-stop growth"],
  ["act deliberately", "act with purpose"],
  ["base every decision on data", "ground every decision"],
  ["real business context", "proven business context"],
  ["get useful results immediately", "see value from day one"],

  // sourced from upworthy.com headlines
  ["he responded", "his response was legendary"],
  ["upset her", "left her in tears"],
  ["he reacts", "his jaw drops"],
  ["will smell better", "will never smell fresher"],
  ["we don't know much about", "there is still much to learn about"],
  ["most people said", "an overwhelming number said"],
  ["was unexpected for them", "went against their very nature"],
  ["got attention", "made her an instant legend"],

  // AI/tech hype slop
  ["uses AI", "is agentic"],
  ["automated", "autonomous"],
  ["chatbot", "AI assistant"],
  ["makes mistakes", "hallucinates"],
  ["works reliably", "hallucination-free"],
  ["fast software", "blazing-fast, next-gen infrastructure"],
  ["new AI model", "frontier model"],
  ["good at coding", "10x engineer-grade"],
  ["big language model", "foundation model"],
  ["uses your data", "trained on proprietary data moats"],
  ["makes decisions", "reasons autonomously"],
  ["combines tools", "orchestrates a multi-agent workflow"],
  ["copies text", "generates novel content"],
  ["basic chatbot", "reasoning engine"],
  ["works okay", "production-grade and enterprise-ready"],
  ["small update", "paradigm-shifting breakthrough"],
  ["might replace some jobs", "will fundamentally reshape the future of work"],
  ["uses a database", "leverages a vector-native knowledge graph"],
  ["prompt", "carefully engineered prompt"],
  ["guesses the next word", "exhibits emergent reasoning"],

  // extra blunt bullshit-calling
  ["nonsense", "thought leadership"],
  ["made up", "visionary"],
  ["lying", "spinning a narrative"],
  ["overpriced", "premium-positioned"],
  ["copied", "inspired by"],
  ["failed", "pivoted"],
  ["ordinary", "best-in-class"],
  ["vague promise", "bold vision"],
  ["buzzword salad", "compelling value proposition"],
  ["empty claim", "market-leading differentiator"],

  // sourced from hubspot.com marketing copy
  ["improve results", "maximize your impact"],
  ["increase revenue", "drive revenue with precision attribution"],
  ["find good leads", "identify high-intent leads"],
  ["send campaigns", "launch cross-channel campaigns"],
  ["speed up results", "accelerate your results"],
  ["show your impact", "prove your business impact"],
  ["make progress", "move the needle"],
  ["give your team data", "empower your team with insights"],
  ["organize conversations", "transform scattered conversations into meaningful relationships"],
  ["get leads fast", "capture higher-quality leads instantly"],
  ["grow a lot", "grow without limits"],
  ["keep improving", "continuously improve your results"],
  ["tell your story", "express your unique brand story"],
  ["easy-to-connect tools", "seamlessly connected tools and experiences"],
  ["personalize automatically", "automate personalized customer experiences"],
  ["win in a busy market", "win in an AI-driven market"],

  // sourced from notion.com marketing copy
  ["find answers fast", "get answers instantly, with citations"],
  ["works around the clock", "keeps work moving 24/7 with agents"],
  ["one place for everything", "one unified system of record"],
  ["popular with big companies", "trusted by the Forbes Cloud 100"],
  ["built-in AI", "AI-native tools"],
  ["good advantage", "important competitive advantage"],
  ["nice design", "thoughtful design that speeds up collaboration"],
  ["help customers faster", "deliver impact to customers faster"],
  ["more than basic AI tasks", "going beyond doing work with AI"],
  ["safe and works at scale", "safe and scalable"],
  ["organize your knowledge", "centralize your knowledge"],
  ["automate boring tasks", "automate busywork"],
  ["written well by AI", "perfectly written by AI"],
  ["search feature", "enterprise search"],
  ["custom bots", "custom agents"],

  // sourced from ibm.com watsonx marketing copy
  ["manage AI tools", "agentic control plane"],
  ["build and manage AI agents", "build, deploy, orchestrate, manage and govern AI agents"],
  ["see everything", "create total visibility"],
  ["expand what works", "scale what works"],
  ["AI everywhere", "AI at scale"],
  ["oversight", "governance and operational oversight"],
  ["find and connect agents", "discover, connect and orchestrate agents"],
  ["control your agents", "bring every agent under control"],
  ["mixed systems", "heterogeneous, hybrid enterprise"],
  ["many different agents", "multi-agent ecosystem"],
  ["one control system", "unified control plane"],
  ["AI systems working together", "AI interoperability"],
  ["disorganized AI projects", "fragmented AI initiatives"],
  ["all your agents", "agentic portfolio"],
  ["turn tests into real tools", "turn successful pilots into reusable, governed capabilities"],

  // sourced from adobe.com Firefly marketing copy
  ["AI content tool", "AI-powered content creation"],
  ["safe to use commercially", "commercially safe"],
  ["high-quality images", "production-quality images"],
  ["exact control", "precise creative control"],
  ["speed up your work", "accelerate creative workflows"],
  ["finish faster", "go from idea to finished asset faster"],
  ["many formats, one tool", "multi-format content from a single platform"],
  ["content that matches your brand", "on-brand campaign content"],
  ["unlock your creativity", "unlock creative potential"],
  ["quick edits", "refine any image in seconds"],
  ["shared workspace", "collaborative visual workspace"],
  ["responsible use of AI", "responsible AI"],
  ["works well with other apps", "deep integration with other apps"],
  ["ready-to-use visuals", "campaign-ready visuals"],
  ["unlimited space", "infinite canvas"],
  ["make a lot at once", "generate at scale"],
  ["professional-quality output", "studio-quality outputs"],
  ["change how you create", "transform your creative process"],

  // plain-English translations for terms flagged by github.com/mourner/bullshit.js
  ["much better", "10x"],
  ["always available", "24/7"],
  ["free time", "bandwidth"],
  ["good method", "best practice"],
  ["lots of data", "big data"],
  ["very new", "bleeding-edge"],
  ["the main point", "bottom line"],
  ["think of ideas", "brainstorm"],
  ["very reliable", "bulletproof"],
  ["request to act", "call to action"],
  ["follow up later", "circle back"],
  ["see the pattern", "connect the dots"],
  ["output", "deliverable"],
  ["explain clearly", "demystify"],
  ["switching to digital tools", "digital transformation"],
  ["look closer", "drill down"],
  ["short pitch", "elevator pitch"],
  ["enthusiastic promoter", "evangelist"],
  ["speed up", "fast track"],
  ["modern-minded", "forward-thinking"],
  ["smooth", "frictionless"],
  ["approach", "game plan"],
  ["detailed", "granular"],
  ["new and important", "ground-breaking"],
  ["expert", "guru"],
  ["briefly", "in a nutshell"],
  ["key metrics", "KPIs"],
  ["lessons", "learnings"],
  ["easy win", "low-hanging fruit"],
  ["public attention", "mind share"],
  ["progress", "momentum"],
  ["obvious choice", "no-brainer"],
  ["does everything", "one-stop-shop"],
  ["ready to use", "out-of-the-box"],
  ["easy to set up", "plug-and-play"],
  ["early test version", "proof of concept"],
  ["go beyond limits", "push the envelope"],
  ["fast success", "quick win"],
  ["redo something already solved", "reinvent the wheel"],
  ["top performer", "rock star"],
  ["check the math", "run the numbers"],
  ["special method", "secret sauce"],
  ["deception", "smoke and mirrors"],
  ["most advanced", "state-of-the-art"],
  ["engaging", "sticky"],
  ["discuss privately later", "take it offline"],
  ["expert", "thought leader"],
  ["output rate", "throughput"],
  ["decided by leadership", "top-down"],
  ["interaction point", "touchpoint"],
  ["growing popularity", "traction"],
  ["ready to use immediately", "turnkey"],
  ["rare, highly valuable startup", "unicorn"],
  ["caught up", "up to speed"],
  ["extra benefit", "value-add"],
  ["good for everyone", "win-win"],
  ["impressive quality", "wow factor"],
  ["current trend", "zeitgeist"],
  ["person involved", "stakeholder"],
  ["agreement", "alignment"],
  ["brainstorming session", "ideation"],
  ["task", "action item"],

  // sourced from mourner.github.io/bullshit.js's own self-demo copy
  ["top-quality", "best-of-breed"],
  ["based on what sells", "market-driven"],
  ["a new way of working", "process-centric innovation"],
  ["talk to our customers", "engage our customers"],
  ["building", "cultivating"],

  // common standalone hype adjectives (also flagged by buzzwords.js's detection list,
  // but needed here too since the AI-unslop banned-word list and mechanical cleanup
  // pass only draw from this dictionary, not the detector)
  ["business", "enterprise"],
  ["new", "innovative"],
  ["can grow", "scalable"],
  ["advanced", "sophisticated"],
  ["great", "exceptional"],
  ["good", "excellent"],
  ["very good", "outstanding"],
  ["unusual", "extraordinary"],
  ["standard", "premium"],
  ["easy to use", "intuitive"],
  ["active", "dynamic"],
  ["convincing", "compelling"],
  ["complete", "comprehensive"],
  ["big", "significant"],
  ["prepared", "proactive"],
  ["top", "leading"],
  ["strong", "powerful"],
  ["effective", "efficient"],
  ["new idea", "innovation"],

  // mined from open PRs on github.com/mourner/bullshit.js (unmerged term suggestions)
  ["designed for phones first", "mobile-first"],
  ["fast", "performant"],
  ["information", "intelligence"],
  ["AI that creates content", "generative AI"],
  ["writing AI instructions", "prompt engineering"],

  // more from upworthy.com headlines
  ["stops them", "stops them in their tracks"],
  ["a good example of", "a timeless example of"],
  ["puts trolls in their place", "shuts down trolls"],
  ["memorable meetings", "unforgettable encounters"],
  ["good comeback", "response that left everyone speechless"],

  // sourced from buzzfeed.com quiz-style clickbait
  ["personality test", "these questions will reveal your true moral alignment"],
  ["guess your background", "we know whether you're X or Y based on this"],
  ["if you know these, you're a fan", "if you can name all of these, you might actually be magical"],
  ["pick your favorites and see what fits you", "design your ideal experience and we'll match you with one"],
  ["short quiz", "personality quiz that will reveal your true self"],

  // gen z internet-speak cringe
  ["definitely", "standing on business"],
  ["it feels like", "it's giving"],
  ["confident", "main character energy"],
  ["feels different", "hits different"],
  ["did it right", "understood the assignment"],
  ["the mood", "the vibes"],
  ["memorable", "living rent free in my head"]
];

// Generalized regex-based patterns for the UNSLOPIFY direction only (matching varied
// real-world slop phrasing found in scraped text - not usable for slopify, since a
// regex pattern like "innovations?" can't safely serve as literal display text).
// Each entry is [slopRegexPattern, plainReplacement], where plainReplacement may be
// a function (matchedText) => string when the correct replacement depends on which
// grammatical form matched (e.g. singular vs plural, to keep subject-verb agreement
// correct) - a static string would be wrong for some matched forms.
//
// IMPORTANT: only combine forms that share the same part of speech in one pattern.
// "innovate/innovating" (verb), "innovative" (adjective), and "innovation" (noun)
// each need a different kind of replacement - collapsing them into one pattern with
// a single replacement function breaks grammar for whichever forms don't fit
// (verified: this bit us once already before this was caught in review).
const GENERALIZED_UNSLOP_PATTERNS = [
  ["innovations?", (matched) => (/s$/i.test(matched) ? "ideas" : "idea")]
];
